# Generated by Django 5.0.4 on 2024-04-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyCacheTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cache_key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField()),
                ("expires", models.DateTimeField()),
            ],
            options={
                "db_table": "my_cache_table",
            },
        ),
    ]
