# Generated by Django 5.0.4 on 2024-04-26 16:00

import ckeditor_uploader.fields
import django.db.models.deletion
import read_statistics.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("last_updated_time", models.DateTimeField(auto_now=True)),
                ("blog_limit", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blog_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.blogtype"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_time"],
            },
            bases=(models.Model, read_statistics.models.ReadNumExpandMethod),
        ),
    ]
