# Generated by Django 5.0.4 on 2024-05-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="标题")),
                (
                    "content",
                    models.TextField(max_length=3000, null=True, verbose_name="内容"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        default="123@123.com", max_length=32, verbose_name="邮箱"
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "avatar",
                    models.CharField(
                        default="http://localhost:8000/static/img/avatar/defaultAvatar.jpg",
                        max_length=256,
                        verbose_name="头像",
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        default="暂时没有个性签名~",
                        max_length=64,
                        null=True,
                        verbose_name="个性签名",
                    ),
                ),
                ("nickname", models.CharField(max_length=20)),
                ("level", models.IntegerField(default=0)),
                (
                    "collected",
                    models.ManyToManyField(
                        blank=True, related_name="collectedPosts", to="user.post"
                    ),
                ),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True, related_name="favoritePosts", to="user.post"
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        blank=True, related_name="beFocusOn", to="user.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="user.user",
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
